// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmsSenderApi.Models;

namespace SmsSenderApi.Migrations
{
    [DbContext(typeof(SmsSenderContext))]
    [Migration("20210224161056_SeedSmsMessageData")]
    partial class SeedSmsMessageData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sms_sender_db")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("SmsSenderApi.Models.SmsMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("SenderName")
                        .HasColumnType("text")
                        .HasColumnName("sender_name");

                    b.Property<DateTime>("SendingDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sending_date");

                    b.Property<string>("SmsId")
                        .HasColumnType("text")
                        .HasColumnName("sms_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("sms_message");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MessageText = "тестовое сообщение2",
                            PhoneNumber = "79270095932",
                            SenderName = "VIRTA",
                            SendingDate = new DateTime(1970, 1, 19, 16, 19, 31, 72, DateTimeKind.Unspecified),
                            SmsId = "510433335",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            MessageText = "тест сообщение4тест сообщение4тест сообщение4тест сообщение4тест сообщение4тест сообщение4",
                            PhoneNumber = "79270095932",
                            SenderName = "VIRTA",
                            SendingDate = new DateTime(1970, 1, 19, 16, 19, 31, 72, DateTimeKind.Unspecified),
                            SmsId = "510434281",
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
